### ISSUE TITLE
broken links in index.html page

### ISSUE THREAD

**Issue by byrneh** [fastai/ghapi#27]
The following api links are invalid and should contain "-" not "_"
https://docs.github.com/en/free-pro-team@latest/rest/reference/code_scanning
https://docs.github.com/en/free-pro-team@latest/rest/reference/codes_of_conduct
https://docs.github.com/en/free-pro-team@latest/rest/reference/enterprise_admin
https://docs.github.com/en/free-pro-team@latest/rest/reference/rate_limit

I did not find an equivalent in GitHub Docs
https://docs.github.com/en/free-pro-team@latest/rest/reference/oauth_authorizations

In GitHub Docs but not in ghapi index.html page
https://docs.github.com/en/free-pro-team@latest/rest/reference/secret-scanning
https://docs.github.com/en/free-pro-team@latest/rest/reference/permissions-required-for-github-apps

**Comment by hamelsmu** [comment]
Thanks for reporting this.  

- [x] I have fixed the broken links due to underscore
- [ ] The  `oauth_authorizations` is an odd thing I'll open a seperate issue for that
- [x] Fixed the secret scanning link that is a new endpoint introduced in the last week
- [x]  "Permissions required for GitHub Apps" is not really an endpoint but a set of guidelines and rules (and TBH those sections of the docs are kind of opaque).

**Comment by hamelsmu** [comment]
cc: @jph00
