### ISSUE TITLE
Authorization error when running from GitHub Actions (and reading from a diff repository)

### ISSUE THREAD

**Issue by choldgraf** [fastai/ghapi#46]
I'm trying to set up a GitHub Action that will create a weekly "team sync" issue for our team, and populate that issue with a few open issues that need attention.

- [here's the action I'm using](https://github.com/2i2c-org/team-compass/blob/main/.github/workflows/create-team-sync.yaml)
- [here's the script that action calls](https://github.com/2i2c-org/team-compass/blob/main/scripts/post-team-sync.py)

I'm using `ghapi` to read lists of issues from a few *other* repositories, and then create an issue in the present repository.

When I run this script locally, it works just fine. However, when run in GitHub Actions, I get an `Unauthorized` error. To try and get around this I've tried to create a Personal Access Token and use it in the script (it is just `ACCESS_TOKEN` in my action above). But this doesn't seem to fix the problem.

I'm curious if anyone has thoughts as to how this could be fixed! [Here's a PR where I am trying t odebug](https://github.com/2i2c-org/team-compass/pull/50).

cc @hamelsmu in case he has experienced this issue with GHA!

**Comment by hamelsmu** [comment]
@choldgraf do you think there is a bug in your script?  In this [line](https://github.com/2i2c-org/team-compass/blob/main/scripts/post-team-sync.py#L29)
It has:

```
api = GhApi(token=github_token())
```
shouldn't it be

```py
api = GhApi(token=token)
```

😄 It would be wonderful if this fixes the issue.  LMK

**Comment by hamelsmu** [comment]
The code of `github_token`() is this 

```py
def github_token():
    "Get GitHub token from `GITHUB_TOKEN` env var if available, or from `github` context"
    return os.getenv('GITHUB_TOKEN', context_github.get('token', None))
```

This means you are trying to getting the `GITHUB_TOKEN` [1] from the actions runner (due to the bug above), which you don't want - basically you want to grab YOUR token you put in `ACCESS_TOKEN`  not the one from the Actions Runner,  The one in the Actions Runner has locked down permissions and won't be able to do what you want.  This will definitely solve your problem. 

[1] I don't think you are getting any token b/c in `create_team_sync.yaml` you are not defining `GITHUB_TOKEN` its just that you have a bug that is trying to grab the wrong environment variable.

**Comment by choldgraf** [comment]
yeeeees!

![](https://media4.giphy.com/media/DffShiJ47fPqM/giphy.gif?cid=ecf05e47mgj699iqmzxul8hatrojpmmyjkkhfa98jcqa1b5r&rid=giphy.gif)

bask in the glory of automated team sync issues: https://github.com/2i2c-org/team-compass/issues/52
